### ISSUE TITLE
Publish package to toltec

### ISSUE THREAD

**Issue by celie56** [bkirwi/sill#1]
As of today I do not see this listed as a package under [entware](https://bin.entware.net/armv7sf-k3.2/Packages.html) or [toltec](https://toltec-dev.org/stable/). Please consider publishing to one of these locations so that this can be installed using [opkg](https://toltec-dev.org/).

**Comment by bkirwi** [comment]
That is an eventual goal, though I don't have a timeline for it!

**Comment by celie56** [comment]
Sounds good. It may also make sense to add a bit more to the build section of the readme if this is open for others to use. I found that the following steps worked for me (as someone who is not that familiar with rust):
```
docker run -it ghcr.io/toltec-dev/rust:v3.0
apt update
apt install git
git clone https://github.com/bkirwi/sill.git
cargo build --release
```

**Comment by Eeems** [comment]
@bkirwi this is now in toltec, so this probably can be closed.
